name: fast-validate
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test-tokio
      run: make test-tokio

    - name: test-smol
      run: make test-smol
